import numpy as np
import time
import warnings

# Base architecture + dimensions
# 5-bar
# 4-bar
# 3-RRR
# 1-DoF Single joint rotationn
# 1-DoF 2 joints coupled rotation (e.g. barrett hand)


def rot_Z(ang):
    r = np.array([[np.cos(ang), -np.sin(ang)], [np.sin(ang), np.cos(ang)]])
    return r


def fin_tip_pos(lengths,ang):
    p = np.zeros(2)
    for i in range(len(lengths)):
        p = p + np.matmul(rot_Z(ang), np.array([0, lengths[i]]))
    return p
        
         
def finger_bend(actu_meth, phal_lengths, R_fg, finger_bases, mult=1):  # Compute range of finger tip positions by bending fingers whilst keeping everything else the same
    workspace = np.empty((0,9))
    if actu_meth == 1:  # if fully-actuated (size=27 iterations)
        for phal_ang1 in np.arange(-np.pi/4, np.pi/4, np.pi/(4*mult**(1./3))):
            for phal_ang2 in np.arange(-np.pi/4, np.pi/4, np.pi/(4*mult**(1./3))):
                for phal_ang3 in np.arange(-np.pi/4, np.pi/4, np.pi/(4*mult**(1./3))):
                    phal_angs = [phal_ang1, phal_ang2, phal_ang3]
                    P_final = np.zeros(9)  # all fingertip positions
                    for fin_count in [0, 1, 2]:
                        P = fin_tip_pos(phal_lengths, phal_angs[fin_count])
                        P_Rot = np.matmul(R_fg[fin_count], np.array([-P[0], 0, P[1]]))
                        # P_final[fin_count] = np.append(finger_bases[fin_count], 0) + np.array([-P_Rot[0], 0, P_Rot[1]])
                        P_final[fin_count*3:(fin_count+1)*3] = np.append(finger_bases[fin_count], 0) + np.array([-P_Rot[0], 0, P_Rot[1]])
                    workspace = np.vstack([workspace, P_final])
        pass
    else:  # if under-actuated (size=27 iterations)
        for phal_ang in np.arange(-np.pi/4, np.pi/4, np.pi/(54*mult)):  # 3 times as many as fully-actuated so arrays are equal size
            P_final = np.zeros(9)  # all fingertip positions
            for fin_count in [0, 1, 2]:
                P = fin_tip_pos(phal_lengths, phal_ang)
                P_Rot = np.matmul(R_fg[fin_count], np.array([-P[0], 0, P[1]]))
                P_final[fin_count * 3:(fin_count + 1) * 3] = np.append(finger_bases[fin_count], 0) + np.array(
                    [-P_Rot[0], 0, P_Rot[1]])
            workspace = np.vstack([workspace, P_final])
    return workspace  # workspace generated by bending fingers in this alignment - workspace = 27 X 3


def five_bar_workspace(l1, l2, theta_range, fin_ori_meth, fin_ori_step, phal_num, phal_lengths, actu_meth):
    workspace = np.zeros((2048, 9))
    P1 = np.array([0, 0])  # base joint positions
    P5 = np.array([d15, 0])
    workspace = np.empty((0, 9))
    theta_step = theta_range/2
    for theta1 in np.arange(0, theta_range, theta_step):  # loop through five bar configurations to obtain base joint positions
        for theta2 in np.arange(0, theta_range, theta_step):
            P2 = P1+l1*np.array([np.cos(theta1), np.sin(theta1)])
            P4 = P5+l1*np.array([np.cos(theta2), np.sin(theta2)])
            d24 = np.sqrt((P4[0]-P2[0])**2+(P4[1]-P2[1])**2)
            if (d24**2+l2**2+l2**2)**2-2*(d24**4+l2**4+l2**4) < 0:
                continue
            A_243 = np.sqrt((d24**2+l2**2+l2**2)**2-2*(d24**4+l2**4+l2**4))/4
            Z_243 = (1/(2*d24**2))*np.array([[d24**2+l2**2-l2**2, -4*A_243], [4*A_243, d24**2+l2**2-l2**2]])
            p24 = P4-P2
            p23 = np.matmul(Z_243, p24)
            P3 = P2 + p23
            p54 = P5-P4
            p43 = P3-P4
            R_fg = [0]*3
            finger_bases = [P2, P3, P4]
            if fin_ori_meth == 0:  # If actuated, loop through finger orientations
                for fin_ori_count1 in range(3):
                    fg_x_ax1 = np.append(np.matmul(rot_Z(-np.pi/2-fin_ori_count1*fin_ori_step), p23/np.linalg.norm(p23)), 0)
                    fg_z_ax1 = np.array([0, 0, 1])
                    fg_y_ax1 = np.cross(fg_z_ax1, fg_x_ax1)
                    R_fg[0] = np.column_stack((fg_x_ax1, fg_y_ax1, fg_z_ax1))
                    for fin_ori_count2 in range(3):
                        fg_x_ax2 = np.append(np.matmul(rot_Z(np.pi/2+fin_ori_count2*fin_ori_step), p54/np.linalg.norm(p54)), 0)
                        fg_z_ax2 = np.array([0, 0, 1])
                        fg_y_ax2 = np.cross(fg_z_ax2, fg_x_ax2)
                        R_fg[1] = np.column_stack((fg_x_ax2, fg_y_ax2, fg_z_ax2))
                        for fin_ori_count3 in range(3):
                            fg_x_ax3 = np.append(np.matmul(rot_Z(np.pi/2+fin_ori_count3*fin_ori_step), p43/np.linalg.norm(p43)), 0)
                            fg_z_ax3 = np.array([0, 0, 1])
                            fg_y_ax3 = np.cross(fg_z_ax3, fg_x_ax3)
                            R_fg[2] = np.column_stack((fg_x_ax3, fg_y_ax3, fg_z_ax3))
                            workspace = np.vstack([workspace, finger_bend(actu_meth, phal_lengths, R_fg, finger_bases)])
            else:  # If passively/spring-driven, compute finger orientations
                C = (P2+P3+P4)/3
                fg_x_ax1 = np.append((C-P2)/np.linalg.norm(C-P2), 0)
                fg_z_ax1 = np.array([0, 0, 1])
                fg_y_ax1 = np.cross(fg_z_ax1, fg_x_ax1)
                R_fg[0] = np.column_stack((fg_x_ax1, fg_y_ax1, fg_z_ax1))
                fg_x_ax2 = np.append((C-P3)/np.linalg.norm(C-P3), 0)
                fg_z_ax2 = np.array([0, 0, 1])
                fg_y_ax2 = np.cross(fg_z_ax2, fg_x_ax2)
                R_fg[1] = np.column_stack((fg_x_ax2, fg_y_ax2, fg_z_ax2))
                fg_x_ax3 = np.append((C-P4)/np.linalg.norm(C-P4), 0)
                fg_z_ax3 = np.array([0, 0, 1])
                fg_y_ax3 = np.cross(fg_z_ax3, fg_x_ax3)
                R_fg[2] = np.column_stack((fg_x_ax3, fg_y_ax3, fg_z_ax3))
                workspace = np.vstack([workspace, finger_bend(actu_meth, phal_lengths, R_fg, finger_bases, mult=27)])
    return workspace


if __name__ == "__main__":

    start_time = time.time()
    warnings.filterwarnings('error')

    five_bar = True

    ######################
    # Five bar linkge
    if five_bar:
        count = 0
        l = 0.1
        workspace_array = []
        fin_ori_meth_array = [0, 1]  # 0=actuated,1=spring-driven
        for l1 in np.arange(0.01, l, 0.03):  # select 5-bar dimensions - l1, l2, d15, theta ranges
            for l2 in np.arange(0.01, l, 0.03):
                for d15 in np.arange(0.01, l, 0.03):
                    for theta_range in np.arange(np.pi/2, 2*np.pi, np.pi/2):
                        for fin_ori_meth in fin_ori_meth_array:
                            for fin_ori_step in np.arange(0, np.pi/2, np.pi/4):  # what size the finger orientation step is
                                for phal_num in [1, 2, 3]:  # select phalange number and lengths
                                    print("time elapsed: {:.2f}s".format(time.time() - start_time), phal_num)
                                    if phal_num == 1:
                                        for phal1 in np.arange(0.025, 0.1, 0.025):
                                            for actu_meth in [0, 1]:  # select actuation method 0=underactutaed, 1=fully-actutaed
                                                workspace = five_bar_workspace(l1, l2, theta_range, fin_ori_meth, fin_ori_step, phal_num, [phal1], actu_meth)
                                                count += 1
                                                np.save('/home/kelin/workspace_kelin/previous_work/WorkspaceArrays/ws'+str(count)+'.npy', workspace)
                                    elif phal_num == 2:
                                        for phal1 in np.arange(0.025, 0.1, 0.025):
                                            for phal2 in np.arange(0.025, 0.1, 0.025):
                                                for actu_meth in [0, 1]:  # select actuation method 0=underactutaed, 1=fully-actutaed
                                                    workspace = five_bar_workspace(l1, l2, theta_range, fin_ori_meth, fin_ori_step, phal_num, [phal1, phal2], actu_meth)
                                                    count += 1
                                                    np.save('/home/kelin/workspace_kelin/previous_work/WorkspaceArrays/ws' + str(count) + '.npy', workspace)
                                    else:
                                        for phal1 in np.arange(0.025, 0.1, 0.025):
                                            for phal2 in np.arange(0.025, 0.1, 0.025):
                                                for phal3 in np.arange(0.025, 0.1, 0.025):
                                                    for actu_meth in [0, 1]:  # select actuation method 0=underactutaed, 1=fully-actutaed
                                                        workspace = five_bar_workspace(l1, l2, theta_range, fin_ori_meth, fin_ori_step, phal_num, [phal1, phal2, phal3], actu_meth)
                                                        count += 1
                                                        np.save('/home/kelin/workspace_kelin/previous_work/WorkspaceArrays/ws' + str(count) + '.npy', workspace)

#    elif four_bar:
#        pass
#    elif three_RRR:
#        pass
#    elif sing_rot:
#        pass
#    elif coup_rot:
#        pass



